"""Types and schemas for Phase 6 Multi-Agent Engineering Runtime."""

import datetime
import uuid
from typing import Any

from pydantic import BaseModel, ConfigDict, Field

from app.models.agent import (
    AgentRoleEnum,
    ReviewCategory,
    ReviewFindingSeverity,
    TaskLifecycleState,
)
from app.schemas.agent import AgentPatchResponse, ImplementationPlan


class ReviewFindingSchema(BaseModel):
    """Structured defect, regression, or security finding generated by the Reviewer Agent."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    severity: ReviewFindingSeverity = Field(
        default=ReviewFindingSeverity.INFO,
        description="Severity level of the finding (CRITICAL, HIGH, MEDIUM, LOW, INFO).",
    )
    category: ReviewCategory = Field(
        default=ReviewCategory.CORRECTNESS,
        description="Category of the finding (SECURITY, REGRESSION, CORRECTNESS, ARCHITECTURE, STYLE, TEST_COVERAGE).",
    )
    file_path: str = Field(..., description="Target file path relative to workspace root.")
    start_line: int | None = Field(default=None, description="Starting line number.")
    end_line: int | None = Field(default=None, description="Ending line number.")
    description: str = Field(..., description="Clear explanation of the finding.")
    evidence: str | None = Field(default=None, description="Code snippet or AST proof.")
    recommendation: str | None = Field(default=None, description="Specific guidance on remediation.")

    model_config = ConfigDict(from_attributes=True)


class AgentReviewSchema(BaseModel):
    """Structured code review evaluation report."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    patch_id: str | None = None
    status: str = Field(default="APPROVED", description="APPROVED or CHANGES_REQUESTED")
    summary: str = Field(..., description="High-level evaluation summary.")
    findings: list[ReviewFindingSchema] = Field(default_factory=list)
    created_at: str = Field(default_factory=lambda: datetime.datetime.now(datetime.UTC).isoformat())
    completed_at: str | None = None

    model_config = ConfigDict(from_attributes=True)


class AgentHandoffPayload(BaseModel):
    """Typed handoff envelope transferred between specialized agents through Orchestrator."""

    source_agent: AgentRoleEnum
    target_agent: AgentRoleEnum
    payload_type: str
    data: dict[str, Any]
    timestamp: str = Field(default_factory=lambda: datetime.datetime.now(datetime.UTC).isoformat())


class AgentTaskCreateRequest(BaseModel):
    """Request payload to initialize an orchestrator-managed multi-agent task."""

    prompt: str = Field(..., min_length=3, max_length=10000, description="Engineering objective for the agent swarm.")
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    session_id: uuid.UUID | None = None
    title: str | None = None


class AgentTaskResponse(BaseModel):
    """Response payload representing an AgentTask lifecycle state."""

    id: uuid.UUID
    session_id: uuid.UUID
    user_id: uuid.UUID
    organization_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    workspace_id: uuid.UUID | None = None
    title: str
    prompt: str
    lifecycle_state: str
    active_agent: str
    iteration_count: int
    tool_call_count: int
    failure_reason: str | None = None
    metadata_json: dict[str, Any] | None = None
    created_at: datetime.datetime
    updated_at: datetime.datetime
    completed_at: datetime.datetime | None = None

    model_config = ConfigDict(from_attributes=True)


__all__ = [
    "AgentHandoffPayload",
    "AgentPatchResponse",
    "AgentReviewSchema",
    "AgentRoleEnum",
    "AgentTaskCreateRequest",
    "AgentTaskResponse",
    "ImplementationPlan",
    "ReviewCategory",
    "ReviewFindingSchema",
    "ReviewFindingSeverity",
    "TaskLifecycleState",
]
