import datetime
import enum
import uuid

from pydantic import BaseModel, Field


class ChangeType(enum.StrEnum):
    CREATE = "CREATE"
    MODIFY = "MODIFY"
    DELETE = "DELETE"
    UNKNOWN = "UNKNOWN"



class AgentChatRequest(BaseModel):
    """Payload for invoking the Forge AI repository intelligence agent."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="User question or inquiry about the codebase.",
    )
    project_id: uuid.UUID = Field(
        ...,
        description="Target project ID providing organizational authorization.",
    )
    repository_id: uuid.UUID | None = Field(
        default=None,
        description="Target repository ID. If omitted, defaults to the project's primary repository.",
    )
    branch_id: uuid.UUID | None = Field(
        default=None,
        description="Target branch ID. If omitted, defaults to the repository's default branch.",
    )
    session_id: uuid.UUID | None = Field(
        default=None,
        description="Optional session ID to reuse existing context. Validated against user and repository.",
    )
    stream: bool = Field(
        default=False,
        description="Whether to stream the agent execution via Server-Sent Events (SSE).",
    )


class AgentSourceReference(BaseModel):
    """Citation or evidence reference returned alongside the agent's answer."""

    file_path: str = Field(..., description="Repository-relative file path of the source.")
    symbol_name: str | None = Field(
        default=None, description="Extracted AST symbol name if applicable."
    )
    start_line: int | None = Field(
        default=None, description="Starting line number of the cited chunk."
    )
    end_line: int | None = Field(default=None, description="Ending line number of the cited chunk.")
    commit_sha: str | None = Field(
        default=None, description="Commit SHA associated with the indexed index version."
    )


class AgentChatMetadata(BaseModel):
    """Operational telemetry and execution metadata for the agent reasoning loop."""

    iterations: int = Field(..., description="Number of agent reasoning turns executed.")
    tool_calls: int = Field(..., description="Total repository tool invocations made.")
    duration_ms: float = Field(..., description="Total execution time in milliseconds.")
    retrieved_sources_count: int = Field(
        ..., description="Total evidence chunks gathered in retrieved context."
    )


class AgentChatResponse(BaseModel):
    """Structured non-streaming response from the Forge AI agent."""

    session_id: uuid.UUID = Field(..., description="Unique agent session ID.")
    project_id: uuid.UUID = Field(..., description="Associated project ID.")
    repository_id: uuid.UUID | None = Field(default=None, description="Bound repository ID.")
    branch_id: uuid.UUID | None = Field(default=None, description="Bound branch ID.")
    answer: str = Field(..., description="Final grounded answer produced by the agent.")
    sources: list[AgentSourceReference] = Field(
        default_factory=list,
        description="Deduplicated source citations gathered during execution.",
    )
    metadata: AgentChatMetadata = Field(
        ..., description="Execution telemetry and performance metadata."
    )


class AgentSessionResponse(BaseModel):
    """Details of an agent operational context session."""

    session_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    created_at: datetime.datetime
    updated_at: datetime.datetime


class AffectedFile(BaseModel):
    """Represents a repository file affected by an implementation plan."""

    file_path: str = Field(..., description="Repository-relative path of the affected file.")
    change_type: ChangeType = Field(
        default=ChangeType.MODIFY,
        description="Type of change: CREATE, MODIFY, DELETE, UNKNOWN.",
    )
    reason: str = Field(..., description="Detailed rationale for why this file must be modified.")
    symbols: list[str] = Field(
        default_factory=list,
        description="Relevant AST symbols (functions, classes, methods) involved.",
    )


class ImplementationPlan(BaseModel):
    """Structured, non-executable engineering plan generated by the planning agent."""

    id: uuid.UUID = Field(default_factory=uuid.uuid4, description="Unique plan identifier.")
    summary: str = Field(..., description="High-level summary of the proposed solution.")
    problem_statement: str = Field(..., description="Identified problem statement and context.")
    approach: str = Field(..., description="Technical approach and architectural strategy.")
    affected_files: list[AffectedFile] = Field(
        default_factory=list,
        description="List of files to be created, modified, or deleted.",
    )
    new_files: list[str] = Field(
        default_factory=list, description="New files to be created."
    )
    deleted_files: list[str] = Field(
        default_factory=list, description="Files to be deleted."
    )
    symbols: list[str] = Field(
        default_factory=list, description="Key symbols impacted across the codebase."
    )
    test_strategy: str = Field(..., description="Strategy for verifying changes via unit/integration tests.")
    risks: list[str] = Field(
        default_factory=list, description="Potential risks, edge cases, and side effects."
    )
    evidence: list[AgentSourceReference] = Field(
        default_factory=list,
        description="Grounded evidence references supporting the plan.",
    )
    created_at: datetime.datetime = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC),
        description="Timestamp when the plan was generated.",
    )



class AgentPlanRequest(BaseModel):
    """Payload for invoking the Planning Agent to generate an ImplementationPlan."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="Feature requirement, issue description, or task description.",
    )
    project_id: uuid.UUID = Field(
        ...,
        description="Target project ID providing organizational authorization.",
    )
    repository_id: uuid.UUID | None = Field(
        default=None,
        description="Target repository ID. If omitted, defaults to project primary repository.",
    )
    branch_id: uuid.UUID | None = Field(
        default=None,
        description="Target branch ID. If omitted, defaults to repository default branch.",
    )
    session_id: uuid.UUID | None = Field(
        default=None,
        description="Optional session ID to bind context to.",
    )


class AgentPlanResponse(BaseModel):
    """Structured response containing generated plan and pending approval gate."""

    session_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    plan: ImplementationPlan
    approval_id: uuid.UUID
    approval_status: str
    created_at: datetime.datetime


class AgentApprovalActionRequest(BaseModel):
    """Payload for approving or rejecting a pending human approval gate."""

    reason: str | None = Field(
        default=None,
        max_length=1000,
        description="Optional justification or feedback for approval decision.",
    )


class AgentApprovalResponse(BaseModel):
    """Details of an AgentApproval record."""

    approval_id: uuid.UUID
    session_id: uuid.UUID
    user_id: uuid.UUID
    approval_type: str
    status: str
    workspace_id: uuid.UUID | None = None
    plan: ImplementationPlan | None = None
    created_at: datetime.datetime
    resolved_at: datetime.datetime | None = None


class AgentWorkspaceCreateRequest(BaseModel):
    """Payload to create an isolated ephemeral AgentWorkspace after plan approval."""

    session_id: uuid.UUID = Field(..., description="Associated AgentSession ID.")
    approval_id: uuid.UUID = Field(..., description="ID of the APPROVED Plan AgentApproval.")


class AgentWorkspaceResponse(BaseModel):
    """Details of an isolated AgentWorkspace."""

    workspace_id: uuid.UUID
    session_id: uuid.UUID
    organization_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    user_id: uuid.UUID
    status: str
    path: str
    base_commit_sha: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    destroyed_at: datetime.datetime | None = None


# --- Phase 5C Schemas: Safe Patch Synthesis & Sandboxed Test Execution ---


class PatchHunk(BaseModel):
    """Structured hunk within a patch file."""

    id: str = Field(..., description="Stable hunk identifier.")
    old_start: int = Field(..., description="1-based starting line number in original file.")
    old_lines: int = Field(..., description="Line count in original file affected by hunk.")
    new_start: int = Field(..., description="1-based starting line number in target file.")
    new_lines: int = Field(..., description="Line count in target file produced by hunk.")
    old_content: str = Field(default="", description="Original code block to be replaced.")
    new_content: str = Field(default="", description="Replacement code block.")


class PatchFile(BaseModel):
    """Structured patch specification for an individual file."""

    file_path: str = Field(..., description="Repository-relative target file path.")
    operation: str = Field(..., description="Patch operation: CREATE, MODIFY, DELETE.")
    old_content_hash: str | None = Field(
        default=None, description="SHA256 hash of original file content for drift detection."
    )
    new_content_hash: str | None = Field(
        default=None, description="SHA256 hash of target file content post-application."
    )
    hunks: list[PatchHunk] = Field(
        default_factory=list, description="Ordered list of non-overlapping patch hunks."
    )
    reason: str | None = Field(
        default=None, description="Detailed rationale for this file modification."
    )


class AgentPatchProposalRequest(BaseModel):
    """Payload to propose a structured patch for validation and diff review."""

    workspace_id: uuid.UUID = Field(..., description="Ephemeral workspace ID.")
    session_id: uuid.UUID = Field(..., description="Agent session ID.")
    summary: str = Field(..., max_length=1024, description="High-level summary of the patch.")
    files: list[PatchFile] = Field(..., description="List of structured file patches.")
    associated_plan_id: uuid.UUID | None = Field(
        default=None, description="ID of approved ImplementationPlan grounding this patch."
    )


class AgentPatchResponse(BaseModel):
    """Structured details of an AgentPatch proposal."""

    patch_id: uuid.UUID
    workspace_id: uuid.UUID
    session_id: uuid.UUID
    status: str
    summary: str
    files: list[PatchFile]
    diff_content: str | None = None
    approval_id: uuid.UUID | None = None
    created_at: datetime.datetime
    applied_at: datetime.datetime | None = None


class PatchDiffResponse(BaseModel):
    """Server-generated unified diff preview."""

    patch_id: uuid.UUID
    workspace_id: uuid.UUID
    unified_diff: str
    files_changed: int
    lines_added: int
    lines_removed: int


class AgentPatchApplyResponse(BaseModel):
    """Result of atomic patch application to workspace."""

    patch_id: uuid.UUID
    workspace_id: uuid.UUID
    status: str
    applied_at: datetime.datetime
    files_modified: list[str]


class TestCommand(BaseModel):
    """Structured declarative test command specification."""

    runner: str = Field(..., description="Allowlisted runner: pytest, ruff, npm_test, npm_build, cargo_test.")
    arguments: list[str] = Field(
        default_factory=list, description="Allowlisted arguments (paths, flags) with no shell operators."
    )
    working_directory: str | None = Field(
        default=None, description="Optional relative subdirectory within workspace."
    )
    timeout_seconds: int = Field(
        default=120, ge=1, le=300, description="Execution timeout in seconds (default 120s)."
    )


class AgentTestExecutionRequest(BaseModel):
    """Payload to execute an allowlisted test runner inside the isolated workspace sandbox."""

    test_command: TestCommand
    session_id: uuid.UUID | None = None
    patch_id: uuid.UUID | None = None


class AgentTestExecutionResponse(BaseModel):
    """Execution report and output from sandboxed test runner."""

    test_id: uuid.UUID
    workspace_id: uuid.UUID
    session_id: uuid.UUID
    patch_id: uuid.UUID | None = None
    test_command: TestCommand
    status: str
    exit_code: int | None = None
    stdout: str | None = None
    stderr: str | None = None
    duration_ms: int | None = None
    started_at: datetime.datetime | None = None
    completed_at: datetime.datetime | None = None


# --- Phase 5D Schemas: Git Branch, Commit & Pull Request Integration ---


class AgentBranchCreateRequest(BaseModel):
    """Payload to create an isolated Git branch within an active workspace."""

    branch_name: str | None = Field(
        default=None,
        description="Optional custom branch name (e.g. forge/issue-42-fix-auth). Defaults to forge/{session_id}.",
    )


class AgentBranchResponse(BaseModel):
    """Details of the created Git branch within the workspace."""

    workspace_id: uuid.UUID
    branch_name: str
    base_commit_sha: str


class AgentGitStatusResponse(BaseModel):
    """Structured server-side Git working tree status."""

    workspace_id: uuid.UUID
    branch_name: str
    base_commit_sha: str
    current_commit_sha: str | None = None
    changed_files: list[str] = Field(default_factory=list)
    staged_files: list[str] = Field(default_factory=list)
    unstaged_files: list[str] = Field(default_factory=list)
    untracked_files: list[str] = Field(default_factory=list)


class AgentCommitRequest(BaseModel):
    """Payload for committing approved workspace changes."""

    message: str | None = Field(
        default=None,
        max_length=1024,
        description="Optional custom commit message.",
    )
    patch_id: uuid.UUID | None = Field(
        default=None,
        description="Associated approved AgentPatch ID.",
    )


class AgentCommitResponse(BaseModel):
    """Details of an approved, recorded Git commit."""

    commit_id: uuid.UUID
    workspace_id: uuid.UUID
    session_id: uuid.UUID
    branch_name: str
    commit_sha: str
    message: str
    created_at: datetime.datetime


class AgentPushRequest(BaseModel):
    """Payload for pushing committed branch to remote repository."""

    remote: str = Field(default="origin", description="Remote name (must be origin).")


class AgentPushResponse(BaseModel):
    """Result of pushing branch to remote repository."""

    workspace_id: uuid.UUID
    branch_name: str
    remote_branch_name: str
    commit_sha: str
    pushed_at: datetime.datetime
    message: str


class AgentPullRequestCreateRequest(BaseModel):
    """Payload for creating a GitHub Pull Request from pushed branch."""

    title: str | None = Field(
        default=None,
        max_length=255,
        description="Optional custom PR title.",
    )
    body: str | None = Field(
        default=None,
        description="Optional custom PR body.",
    )
    base_branch: str | None = Field(
        default=None,
        description="Target base branch (defaults to repository default branch).",
    )


class AgentPullRequestResponse(BaseModel):
    """Details of an approved GitHub Pull Request."""

    pr_id: uuid.UUID
    workspace_id: uuid.UUID
    session_id: uuid.UUID
    repository_id: uuid.UUID
    branch_name: str
    base_branch: str
    commit_sha: str
    github_pr_number: int | None = None
    github_pr_url: str | None = None
    title: str
    body: str
    status: str
    created_at: datetime.datetime



