import datetime
import enum
import uuid

from pydantic import BaseModel, Field


class ChangeType(enum.StrEnum):
    CREATE = "CREATE"
    MODIFY = "MODIFY"
    DELETE = "DELETE"
    UNKNOWN = "UNKNOWN"



class AgentChatRequest(BaseModel):
    """Payload for invoking the Forge AI repository intelligence agent."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="User question or inquiry about the codebase.",
    )
    project_id: uuid.UUID = Field(
        ...,
        description="Target project ID providing organizational authorization.",
    )
    repository_id: uuid.UUID | None = Field(
        default=None,
        description="Target repository ID. If omitted, defaults to the project's primary repository.",
    )
    branch_id: uuid.UUID | None = Field(
        default=None,
        description="Target branch ID. If omitted, defaults to the repository's default branch.",
    )
    session_id: uuid.UUID | None = Field(
        default=None,
        description="Optional session ID to reuse existing context. Validated against user and repository.",
    )
    stream: bool = Field(
        default=False,
        description="Whether to stream the agent execution via Server-Sent Events (SSE).",
    )


class AgentSourceReference(BaseModel):
    """Citation or evidence reference returned alongside the agent's answer."""

    file_path: str = Field(..., description="Repository-relative file path of the source.")
    symbol_name: str | None = Field(
        default=None, description="Extracted AST symbol name if applicable."
    )
    start_line: int | None = Field(
        default=None, description="Starting line number of the cited chunk."
    )
    end_line: int | None = Field(default=None, description="Ending line number of the cited chunk.")
    commit_sha: str | None = Field(
        default=None, description="Commit SHA associated with the indexed index version."
    )


class AgentChatMetadata(BaseModel):
    """Operational telemetry and execution metadata for the agent reasoning loop."""

    iterations: int = Field(..., description="Number of agent reasoning turns executed.")
    tool_calls: int = Field(..., description="Total repository tool invocations made.")
    duration_ms: float = Field(..., description="Total execution time in milliseconds.")
    retrieved_sources_count: int = Field(
        ..., description="Total evidence chunks gathered in retrieved context."
    )


class AgentChatResponse(BaseModel):
    """Structured non-streaming response from the Forge AI agent."""

    session_id: uuid.UUID = Field(..., description="Unique agent session ID.")
    project_id: uuid.UUID = Field(..., description="Associated project ID.")
    repository_id: uuid.UUID | None = Field(default=None, description="Bound repository ID.")
    branch_id: uuid.UUID | None = Field(default=None, description="Bound branch ID.")
    answer: str = Field(..., description="Final grounded answer produced by the agent.")
    sources: list[AgentSourceReference] = Field(
        default_factory=list,
        description="Deduplicated source citations gathered during execution.",
    )
    metadata: AgentChatMetadata = Field(
        ..., description="Execution telemetry and performance metadata."
    )


class AgentSessionResponse(BaseModel):
    """Details of an agent operational context session."""

    session_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    created_at: datetime.datetime
    updated_at: datetime.datetime


class AffectedFile(BaseModel):
    """Represents a repository file affected by an implementation plan."""

    file_path: str = Field(..., description="Repository-relative path of the affected file.")
    change_type: ChangeType = Field(
        default=ChangeType.MODIFY,
        description="Type of change: CREATE, MODIFY, DELETE, UNKNOWN.",
    )
    reason: str = Field(..., description="Detailed rationale for why this file must be modified.")
    symbols: list[str] = Field(
        default_factory=list,
        description="Relevant AST symbols (functions, classes, methods) involved.",
    )


class ImplementationPlan(BaseModel):
    """Structured, non-executable engineering plan generated by the planning agent."""

    id: uuid.UUID = Field(default_factory=uuid.uuid4, description="Unique plan identifier.")
    summary: str = Field(..., description="High-level summary of the proposed solution.")
    problem_statement: str = Field(..., description="Identified problem statement and context.")
    approach: str = Field(..., description="Technical approach and architectural strategy.")
    affected_files: list[AffectedFile] = Field(
        default_factory=list,
        description="List of files to be created, modified, or deleted.",
    )
    new_files: list[str] = Field(
        default_factory=list, description="New files to be created."
    )
    deleted_files: list[str] = Field(
        default_factory=list, description="Files to be deleted."
    )
    symbols: list[str] = Field(
        default_factory=list, description="Key symbols impacted across the codebase."
    )
    test_strategy: str = Field(..., description="Strategy for verifying changes via unit/integration tests.")
    risks: list[str] = Field(
        default_factory=list, description="Potential risks, edge cases, and side effects."
    )
    evidence: list[AgentSourceReference] = Field(
        default_factory=list,
        description="Grounded evidence references supporting the plan.",
    )
    created_at: datetime.datetime = Field(
        default_factory=lambda: datetime.datetime.now(datetime.UTC),
        description="Timestamp when the plan was generated.",
    )



class AgentPlanRequest(BaseModel):
    """Payload for invoking the Planning Agent to generate an ImplementationPlan."""

    message: str = Field(
        ...,
        min_length=1,
        max_length=4000,
        description="Feature requirement, issue description, or task description.",
    )
    project_id: uuid.UUID = Field(
        ...,
        description="Target project ID providing organizational authorization.",
    )
    repository_id: uuid.UUID | None = Field(
        default=None,
        description="Target repository ID. If omitted, defaults to project primary repository.",
    )
    branch_id: uuid.UUID | None = Field(
        default=None,
        description="Target branch ID. If omitted, defaults to repository default branch.",
    )
    session_id: uuid.UUID | None = Field(
        default=None,
        description="Optional session ID to bind context to.",
    )


class AgentPlanResponse(BaseModel):
    """Structured response containing generated plan and pending approval gate."""

    session_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    plan: ImplementationPlan
    approval_id: uuid.UUID
    approval_status: str
    created_at: datetime.datetime


class AgentApprovalActionRequest(BaseModel):
    """Payload for approving or rejecting a pending human approval gate."""

    reason: str | None = Field(
        default=None,
        max_length=1000,
        description="Optional justification or feedback for approval decision.",
    )


class AgentApprovalResponse(BaseModel):
    """Details of an AgentApproval record."""

    approval_id: uuid.UUID
    session_id: uuid.UUID
    user_id: uuid.UUID
    approval_type: str
    status: str
    workspace_id: uuid.UUID | None = None
    plan: ImplementationPlan | None = None
    created_at: datetime.datetime
    resolved_at: datetime.datetime | None = None


class AgentWorkspaceCreateRequest(BaseModel):
    """Payload to create an isolated ephemeral AgentWorkspace after plan approval."""

    session_id: uuid.UUID = Field(..., description="Associated AgentSession ID.")
    approval_id: uuid.UUID = Field(..., description="ID of the APPROVED Plan AgentApproval.")


class AgentWorkspaceResponse(BaseModel):
    """Details of an isolated AgentWorkspace."""

    workspace_id: uuid.UUID
    session_id: uuid.UUID
    organization_id: uuid.UUID
    project_id: uuid.UUID
    repository_id: uuid.UUID
    branch_id: uuid.UUID | None = None
    user_id: uuid.UUID
    status: str
    path: str
    base_commit_sha: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    destroyed_at: datetime.datetime | None = None

